# Site settings
title: "Steward's Resume"
description: "Steward's Resume, update Oct. 6, 2023"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Steward Sea"
resume_title:                   "Java Developer(Full Stack)"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "seesea2024@google.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+86)182-0199-1089"
resume_contact_address:         "Shanghai, China"

resume_header_contact_info:     "(+86)182-0199-1089 | Shanghai, China | <a href="mailto:seesea2024@gmail.com">seesea2024@gmail.com</a>"
display_header_contact_info:    "true"

resume_header_intro: "<p>Java Developer with more than 10 years of experience on Core Java, Spring MVC, Spring Boot, MySQL, Redis, Kafka, Micro Service, html, JavaScript, VueJS, etc.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/seesea2024/resume-template"
  resume_twitter_url:           "https://twitter.com/seesea2024"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
